# Download the latest MSIX packages from Microsoft Store and upload them to GitHub release.
# See: https://github.com/JasonWei512/Upload-Microsoft-Store-MSIX-Package-to-GitHub-Release

name: Upload store MSIX to release

on: 
  release:  
    types: [released]   # Run the action when a GitHub release is published

  schedule:
    - cron:  '0 */6 * * *'  # Run the action every 6 hours

  workflow_dispatch:    # Manually run the action

jobs:
  upload-store-msix-to-release:
    runs-on: ubuntu-latest

    steps:
    - name: Upload store MSIX to release
      uses: JasonWei512/Upload-Microsoft-Store-MSIX-Package-to-GitHub-Release@v1
      with:
        store-id: 9PM0GCZ6ZD53
        token: ${{ secrets.GITHUB_TOKEN }}
        asset-name-pattern: SpocHelper_{version}_{arch}